### ISSUE TITLE
Cache nodes and pointer values

### ISSUE THREAD

**Issue by bbkr** [bbkr/GeoIP2#26]
Experimental branch that allows to cache binary tree nodes and data pointed by pointers is ready:

https://github.com/bbkr/GeoIP2/tree/node_cache
(no docs or tests yet)

It gives excellent boost (up to 400%), however random replacement retention policy used suffers from low performance on Hash.pick reported in: https://github.com/rakudo/rakudo/issues/2586

So when retention takes place on large cache it can have very negative impact on overall performance.

Waiting for Rakudo task to be addressed, then I'll decide if this will be suitable for merge.

**Comment by bbkr** [comment]
BTW: 100% pointer cache hits does **NOT** reduce syscalls to 0, because sometimes pointer is stored not only on control byte but also on following bytes.

**Comment by lizmat** [comment]
Looking at your code, and assuming you want to keep the "remove random value from hash" feature, I suggest the following:

if cache-size exceeded
    is there a list of keys already?
      if no, make a list of keys in the hash
    use .grab to get a random value from the list of keys
    remove that value from the hash
...
when adding new value to cache
   is there a list of keys?
      add new value to list as well

Does that make sense?  This way there should be minimal overhead until you actually fill up the cache, and minimal overhead after that.

**Comment by lizmat** [comment]
Alternately, if you don't care too much about the randomness, you could just remove the first key in .keys:

    %hash.DELETE-KEY(%hash.iterator.pull-one.key)

would be the faster HLL way of doing this.

**Comment by bbkr** [comment]
I'll try bulk freeing strategy - when cache is full free 10% of keys in one go.

Your array of keys list would require expensive removal from such list.
I'm not convinced this will be better on big arrays.

I've already tried removal of first key - that doesn't give good distribution. 

Thanks for suggestions!

**Comment by bbkr** [comment]
Note:

Locating 500_000 of real, international www traffic on infinite node cache against pro database:

```
Speed: 141.75/s
Found: 498351 (99.67%)
Node cache: {hits => 11120970, misses => 923200}
```

So maybe... node cache does not need any retention? Any modern machine should be capable of storing few MBs of nodes in memory.

**Comment by bbkr** [comment]
After one year of using this module I don't think there is any reason to merge this branch. It complicates code and even better results can be achieved by simply putting whole GeoIP database on RAM disk for blazingly fast I/O.
